# Generated by Django 6.0.1 on 2026-02-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_customer_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='活动ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='副标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='封面')),
                ('poster', models.CharField(blank=True, max_length=500, null=True, verbose_name='海报')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击数')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('participants', models.IntegerField(default=0, verbose_name='参与人数')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='属性组名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '属性组',
                'verbose_name_plural': '属性组',
                'db_table': 'attribute_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, verbose_name='属性值')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '属性值',
                'verbose_name_plural': '属性值',
                'db_table': 'attribute_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('rating', models.SmallIntegerField(verbose_name='评分')),
                ('content', models.TextField(verbose_name='内容')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(verbose_name='评论时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('created_at', models.DateTimeField(verbose_name='点赞时间')),
            ],
            options={
                'verbose_name': '评论点赞',
                'verbose_name_plural': '评论点赞',
                'db_table': 'comment_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('created_at', models.DateTimeField(verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='商品ID')),
                ('category', models.CharField(max_length=20, verbose_name='分类')),
                ('tag', models.CharField(max_length=50, verbose_name='标签')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='副标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='详情')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片URL')),
                ('images', models.TextField(blank=True, null=True, verbose_name='其他图片（JSON数组或逗号分隔URL）')),
                ('taobao_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='淘宝链接')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态：1-上架，0-下架')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=50, verbose_name='属性名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品属性',
                'verbose_name_plural': '商品属性',
                'db_table': 'product_attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, verbose_name='属性值')),
                ('price_adjust', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格调整')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品属性值',
                'verbose_name_plural': '商品属性值',
                'db_table': 'product_attribute_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='SKU名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='SKU图片')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态：1-启用，0-禁用')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
                'db_table': 'product_skus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSkuValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'SKU属性值',
                'verbose_name_plural': 'SKU属性值',
                'db_table': 'product_sku_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=50, verbose_name='规格名称')),
                ('spec_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格值')),
                ('price_adjust', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格调整')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
                'db_table': 'product_specs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, verbose_name='组合Key')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='组合价格')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品组合价格',
                'verbose_name_plural': '商品组合价格',
                'db_table': 'product_variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='门店名称')),
                ('address', models.CharField(max_length=500, verbose_name='门店地址')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('hours', models.CharField(blank=True, max_length=50, null=True, verbose_name='营业时间')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
                'db_table': 'stores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '天气记录',
                'verbose_name_plural': '天气记录',
                'db_table': 'weather',
                'managed': False,
            },
        ),
    ]
